CREATE TABLE products (
  id int(11) NOT NULL AUTO_INCREMENT COMMENT 'id товара в базе',
  offer_id varchar(32) NOT NULL COMMENT 'id товара в системе',
  hub_stock_id varchar(32) DEFAULT NULL COMMENT 'id оригинала товара',
  available tinyint(4) DEFAULT NULL COMMENT 'наличие',
  vendorCode int(11) DEFAULT NULL COMMENT 'артикул (код товара)',
  name varchar(256) NOT NULL COMMENT 'название',
  renew_date timestamp NULL DEFAULT NULL COMMENT 'дата последнего обновления наличия',
  insert_date timestamp NULL DEFAULT current_timestamp(),
  group_id varchar(32) DEFAULT NULL COMMENT 'id группы разновидностей',
  categoryId int(11) NOT NULL COMMENT 'id категории',
  prom_cat_id int(11) DEFAULT NULL,
  portal_category_id int(11) DEFAULT NULL COMMENT 'id категории prom',
  portal_category_url varchar(256) DEFAULT NULL COMMENT 'название категории prom',
  price float NOT NULL COMMENT 'цена (актуальная)',
  oldprice float DEFAULT NULL COMMENT 'цена (без скидки)',
  prod_commission float DEFAULT NULL,
  cpa_saldo float DEFAULT NULL,
  force_rk_type enum('CPC','CPA') DEFAULT NULL,
  minimum_order_quantity int(11) DEFAULT 1 COMMENT 'минимальное кол-во в заказе',
  quantity_in_stock int(11) DEFAULT NULL COMMENT 'кол-во на складе',
  currencyId enum('RUB','UAH','BYR','KZT','EUR','USD') DEFAULT 'UAH' COMMENT 'валюта',
  vendor varchar(128) DEFAULT NULL COMMENT 'производитель',
  country varchar(32) DEFAULT NULL COMMENT 'страна-производитель',
  description mediumtext DEFAULT NULL COMMENT 'описание',
  prod_blacklist tinyint(4) DEFAULT 0 COMMENT 'в блэк-листе',
  top tinyint(4) DEFAULT 0 COMMENT 'в топе',
  vendor_id int(11) DEFAULT NULL COMMENT 'поставщик',
  presence_sure tinyint(4) DEFAULT 1 COMMENT 'гарант. наличие',
  source_id int(11) DEFAULT NULL COMMENT 'кто поставляет товар',

  GTIN bigint(20) DEFAULT NULL,
  PRIMARY KEY (id) USING BTREE,
  UNIQUE KEY offer_id (offer_id) USING BTREE,
  UNIQUE KEY hub_stock_id (hub_stock_id) USING BTREE,
  UNIQUE KEY vendorCode (vendorCode) USING BTREE,
  KEY vendor_id (vendor_id) USING BTREE,
  KEY price (price) USING BTREE,
  KEY category_id (categoryId) USING BTREE,
  KEY prod_blacklist (prod_blacklist) USING BTREE,
  KEY available (available) USING BTREE,
  KEY top (top) USING BTREE,
  KEY prod_commission (prod_commission) USING BTREE,
  KEY renew_date (renew_date) USING BTREE,
  KEY prom_cat_id (prom_cat_id) USING BTREE,
  KEY force_rk_type (force_rk_type) USING BTREE,
  KEY source_id (source_id) USING BTREE,
  KEY name_2 (name), FULLTEXT KEY name (name),
  -- CONSTRAINT products_ibfk_1 FOREIGN KEY (vendor_id) REFERENCES product_vendors (id)
) ENGINE=InnoDB AUTO_INCREMENT=1249524 DEFAULT CHARSET=utf8;
