table! {
    products (id) {
        id -> Integer,
        offer_id -> Varchar,
        hub_stock_id -> Nullable<Varchar>,
        categoryId -> Integer,
        name -> Varchar,
        price -> Float,
        oldprice -> Nullable<Float>,
        currencyId -> Nullable<Varchar>,
        available -> Nullable<Tinyint>,
        description -> Nullable<Mediumtext>,
//        vendorCode -> Nullable<Integer>,
        renew_date -> Nullable<Timestamp>,
//        insert_date -> Nullable<Timestamp>,
//        group_id -> Nullable<Varchar>,
//        prom_cat_id -> Nullable<Integer>,
//        portal_category_id -> Nullable<Integer>,
//        portal_category_url -> Nullable<Varchar>,
//        prod_commission -> Nullable<Float>,
//        cpa_saldo -> Nullable<Float>,
//        // force_rk_type -> Nullable<Enum>,
//        minimum_order_quantity -> Nullable<Integer>,
//        quantity_in_stock -> Nullable<Integer>,
//        vendor -> Nullable<Varchar>,
//        country -> Nullable<Varchar>,
//        prod_blacklist -> Nullable<Tinyint>,
//        top -> Nullable<Tinyint>,
//        vendor_id -> Nullable<Integer>,
//        presence_sure -> Nullable<Tinyint>,
//        source_id -> Nullable<Integer>,
//        GTIN -> Nullable<Bigint>,
    }
}
